version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx:/etc/nginx/conf.d"
      - "html:/usr/share/nginx/html"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs:ro"
      - "htpasswd:/etc/nginx/htpasswd"
      
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    environment:
      - DHPARAM_GENERATION=false
      
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always
    volumes:
      - "nginx:/etc/nginx/conf.d"
      - "html:/usr/share/nginx/html"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs:rw"
      
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - "nginx-proxy"

volumes:
  nginx:
  html:
  vhost:
  certs:
  htpasswd:
     
networks:
  default:
    external:
      name: nginx-proxy
