version: '3'

services:
   code-server:
    image: codercom/code-server:v2
    container_name: code-server
    restart: unless-stopped
    command:
      --allow-http
    volumes:
      - "code-server:/home/user"
    expose"
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`ide.${DOMAIN}`)"
      - "traefik.port=8080"
      - "traefik.http.services.code-server.loadbalancer.server.port=3000"
      - "traefik.protocol=http" 

      - "traefik.frontend.headers.SSLRedirect=true" 
      - "traefik.frontend.headers.STSSeconds=315360000" 
      - "traefik.frontend.headers.browserXSSFilter=true" 
      - "traefik.frontend.headers.contentTypeNosniff=true" 
      - "traefik.frontend.headers.forceSTSHeader=true" 
      - "traefik.frontend.headers.SSLHost=${DOMAIN}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true" 
      - "traefik.frontend.headers.frameDeny=true"

      - "traefik.http.routers.code-server.middlewares=admin-auth"
      - "traefik.http.routers.code-server.entrypoints=websecure"
    #   - "traefik.http.routers.code-server.tls.certresolver=mytlschallenge"

      - "traefik.docker.network=traefik"

volumes:
  code-server:
     
networks:
  traefik:
    external: true