version: '3'

services:
   code-server:
    image: codercom/code-server:v2
    container_name: code-server
    restart: unless-stopped
    volumes:
      - "code-server:/home/coder/project"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`ide.${DOMAIN}`)"
      - "traefik.http.routers.code-server.middlewares=admin-auth"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.tls.certresolver=mytlschallenge"
      - "traefik.http.services.code-server.loadbalancer.server.port=8080"

volumes:
  code-server:
     
networks:
  default:
    external:
      name: traefik
