version: '3'

services:
  registry:
    image: registry:2
    container_name: registry
    expose:
      - 5000
    volumes:
      - "registry-data:/var/lib/registry"
      - "registry-config:/etc/docker/registry"
      - "registry-auth:/auth"
      - "certs:/etc/nginx/certs:ro"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`registry.${DOMAIN}`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls.certresolver=mytlschallenge"

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    expose:
      - 80
    depends_on:
      - registry
    environment: 
      - VIRTUAL_HOST=ui.registry.${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=registry.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-ui.rule=Host(`ui.registry.${DOMAIN}`)"
      - "traefik.http.routers.registry-ui.entrypoints=websecure"
      - "traefik.http.routers.registry-ui.tls.certresolver=mytlschallenge"

volumes:
  registry-data:
  registry-config:
  registry-auth:
     
networks:
  default:
    external:
      name: nginx-proxy
