version: '3'

services:      
  code:
    image: codercom/code-server:v2
    container_name: code
    restart: always
    volumes:
      - "./:/home/coder/project"
    environment:
     - VIRTUAL_HOST=code.${DOMAIN}
     - VIRTUAL_PORT=8080
     - LETSENCRYPT_HOST=code.${DOMAIN}
     - LETSENCRYPT_EMAIL=${EMAIL}

networks:
  default:
    external:
      name: nginx-proxy
