version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "html:/usr/share/nginx/html"
      - "vhost:/etc/nginx/vhost.d"
      - "ssl:/etc/nginx/certs:ro"
      - "htpasswd:/etc/nginx/htpasswd"
      - "./nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    env_file: nginx-proxy.env
      
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always
    volumes:
      - "html:/usr/share/nginx/html"
      - "vhost:/etc/nginx/vhost.d"
      - "ssl:/etc/nginx/certs:rw"
      - "./nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - "nginx-proxy"
    env_file: nginx-proxy.env
        
volumes:
  vhost:
  html:
  ssl:
  htpasswd:

networks:
  default:
    external:
      name: nginx-proxy
