version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/nginx/conf:/etc/nginx/conf.d"
      - "./data/nginx/html:/usr/share/nginx/html"
      - "./data/nginx/vhost:/etc/nginx/vhost.d"
      - "./data/nginx/certs:/etc/nginx/certs:ro"
      - "./data/nginx/htpasswd:/etc/nginx/htpasswd"
      
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    env_file: nginx-proxy.env
      
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always
    volumes:
      - "./data/nginx/conf:/etc/nginx/conf.d"
      - "./data/nginx/html:/usr/share/nginx/html"
      - "./data/nginx/vhost:/etc/nginx/vhost.d"
      - "./data/nginx/certs:/etc/nginx/certs:rw"
      
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - "nginx-proxy"
    env_file: nginx-proxy.env

networks:
  default:
    external:
      name: nginx-proxy
