version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file: postgres.env
    volumes:
       - postgres:/data/postgres
    expose:
      - 5432
    restart: always
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: postgres.env
    volumes:
       - pgadmin:/root/.pgadmin
    restart: always
    environment:
     - VIRTUAL_HOST=postgres.${DOMAIN}
     - VIRTUAL_PORT=5050
     - LETSENCRYPT_HOST=postgres.${DOMAIN}
     - LETSENCRYPT_EMAIL=${EMAIL}


volumes:
  vhost:
  html:
  ssl:
  htpasswd:
  portainer:
  registry:
  drone:
  postgres:
  pgadmin:

networks:
  default:
    external:
      name: nginx-proxy
