version: '3'

services:
   gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    volumes:
      - "gitea:/data"
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.code-server.rule=Host(`git.${DOMAIN}`)"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.tls.certresolver=mytlschallenge"
      

volumes:
  gitea:
     
networks:
  traefik:
    external: true