version: '3'

services:
  adminer:
    image: adminer
    container_name: adminer
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    environment: 
      - VIRTUAL_HOST=db.${DOMAIN}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=db.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`db.${DOMAIN}`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=mytlschallenge"


networks:
  default:
    external:
      name: nginx-proxy
