version: '3'

  postgres:
    container_name: postgres
    image: postgres
    env_file: postgres.env
    volumes:
       - postgres:/data/postgres
    expose:
      - 5432
    restart: always
  
volumes:
  postgres:
     
networks:
  default:
    external:
      name: nginx-proxy
